package:
  name: clusterutils
  version: !!str dev

source:
   git_url: https://github.com/choderalab/clusterutils

build:
  entry_points:
    - build_mpirun_configfile = clusterutils.build_mpirun_configfile:main

requirements:
  build:
    - python
    - distribute

  run:
    - python

about:
  home: https://github.com/choderalab/clusterutils
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
